# Stage 1: Build the frontend
FROM node:20 AS builder

WORKDIR /app
COPY ../blogify-frontend/package*.json ./
RUN npm install
COPY ../blogify-frontend .
RUN npm run build

# Stage 2: Serve with lightweight image
FROM node:20-alpine AS runner

WORKDIR /app
COPY --from=builder /app .

EXPOSE 3000
CMD ["npm", "run", "start"]
