# Use Node.js official image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY ../backend/package*.json ./
RUN npm install

# Copy the rest of the backend code
COPY ../backend .

# Expose the backend port
EXPOSE 5000

# Start the server
CMD ["npm", "run", "dev"]
